<? require('./frames/header.php'); ?>
<h2>部員紹介</h2>
<h3>幹部</h3>
<table class="newstable"  border="2">
    <tr>
        <th>学部</th>
        <th>学科</th>
        <th>学年</th>
        <th>役職</th>
        <th>パート</th>
        <th>名前</th>
    </tr>
    <tr>
        <td>法学部</td>
        <td>法律</td>
        <td>2年</td>
        <td>ヒラ</th>
        <td>ギター</td>
        <td>上山航輝</td> 
    </tr>
    <tr>
        <td>法学部</td>
        <td>法律</td>
        <td>2年</td>
        <td>ヒラ</th>
        <td>ギター</td>
        <td>上山航輝</td> 
    </tr>
</table>
<h3>部員</h3>
<table class="newstable"  border="2">
    <tr>
        <th>学部</th>
        <th>学科</th>
        <th>学年</th>
        <th>パート</th>
        <th>名前</th>
    </tr>
    <tr>
        <td>法学部</td>
        <td>法律</td>
        <td>2年</td>
        <td>ギター</td>
        <td>上山航輝</td> 
    </tr>
    <tr>
        <td>法学部</td>
        <td>法律</td>
        <td>2年</td>
        <td>ギター</td>
        <td>上山航輝</td> 
    </tr>
</table>